# Generated by Django 5.0.6 on 2024-10-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Администратор', 'Администратор'), ('Директор', 'Директор'), ('Кассир', 'Кассир'), ('Стажер', 'Стажер'), ('Курьер', 'Курьер'), ('Смм', 'Смм'), ('Прочее', 'Прочее')], default='Прочее', max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
