# Generated by Django 5.0.6 on 2024-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID группы')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус интеграции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Группа Telegram',
                'verbose_name_plural': 'Группы Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя')),
                ('user_id', models.CharField(max_length=200, verbose_name='ID пользователя telegram')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('user_role', models.CharField(choices=[('User', 'Пользователь'), ('Delivery', 'Курьер'), ('Manager', 'Менеджер'), ('Waiter', 'Официант')], default='Пользователь', max_length=100, verbose_name='Роль пользователя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
