# Generated by Django 5.0.6 on 2024-09-20 05:53

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы О нас')),
                ('description', models.CharField(max_length=855, verbose_name='Описание страницы О нас')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Фотография')),
                ('exp', models.CharField(max_length=55, verbose_name='Опыт работы')),
                ('promo_title', models.CharField(max_length=255, verbose_name='Заголовок промо')),
                ('promo_desc', models.CharField(max_length=255, verbose_name='Описание промо')),
                ('promo_video', models.FileField(upload_to='about_us/', verbose_name='Промо видео')),
                ('promo_image', models.FileField(upload_to='about_us/', verbose_name='Промо фото ')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='ФИО сотрудника')),
                ('job_title', models.CharField(max_length=55, verbose_name='Должность')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Фотография')),
                ('tweeter', models.URLField(blank=True, null=True, verbose_name='Ссылка на Tweeter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на telegram')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='FactsAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, verbose_name='Номер факта')),
                ('title', models.CharField(max_length=55, verbose_name='Факт')),
                ('text', models.CharField(max_length=150, verbose_name='Текст факта')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='MainPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Количество посещений')),
            ],
            options={
                'verbose_name': 'Посещение главной страницы',
                'verbose_name_plural': 'Посещения главной страницы',
            },
        ),
        migrations.CreateModel(
            name='MenuVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Количество посещений')),
            ],
            options={
                'verbose_name': 'Посещение меню',
                'verbose_name_plural': 'Посещения меню',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Имя отправителя')),
                ('message', models.CharField(max_length=500, verbose_name='Текст отправителя')),
            ],
            options={
                'verbose_name': 'Сообщение от пользователя',
                'verbose_name_plural': 'Сообщения от пользователей',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('amount', models.IntegerField(verbose_name='Сумма промокода')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания промокода')),
            ],
            options={
                'verbose_name': 'Промокод (скидка на сайте)',
                'verbose_name_plural': 'Промокоды (скидки на сайте)',
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=55, null=True, verbose_name='Под загаловок')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст промоакции')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Фотография')),
                ('url', models.URLField(verbose_name='Ссылка на промоакцию')),
            ],
            options={
                'verbose_name': 'Промоакция',
                'verbose_name_plural': 'Промоакции',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Фотография')),
                ('mobile_logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Фотография')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('telegram_group_chat_id', models.IntegerField(blank=True, null=True, verbose_name='ID чата telegram')),
                ('menu_telegram_group_chat_id', models.IntegerField(blank=True, null=True, verbose_name='ID чата menu telegram')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
