# Generated by Django 5.0.6 on 2024-09-20 05:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='crm_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='CRM лого'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mobile_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='uploads/', verbose_name='Мобильное лого'),
        ),
    ]
