# Generated by Django 5.0.6 on 2024-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_billing_volume_product_billing_weight_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='delivery_date_time',
        ),
        migrations.AlterField(
            model_name='billing',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
