# Generated by Django 5.0.6 on 2024-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_billing_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_source',
            field=models.CharField(choices=[('Сайт', 'Сайт'), ('Инстаграм', 'Инстаграм'), ('Ватсапп', 'Ватсапп'), ('Телеграм', 'Телеграм')], default='Сайт', max_length=100, verbose_name='Источник'),
        ),
    ]
