# Generated by Django 5.0.6 on 2024-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(verbose_name='User-Agent')),
                ('url_path', models.CharField(max_length=255, verbose_name='URL страницы')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время посещения')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-timestamp'],
            },
        ),
    ]
