# Generated by Django 5.0.6 on 2024-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_employee_city'),
        ('kanban', '0002_alter_card_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='employee_cards', to='erp.employee', verbose_name='Участники'),
        ),
    ]
