# Generated by Django 5.0.6 on 2024-11-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_remove_card_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивация'),
        ),
    ]
